### ISSUE TITLE
Bring back the inspector 👍 

### ISSUE THREAD

**Issue by delight** [skeletonlabs/create-skeleton-app#19]
With the switch switch to clack the option for the inspector got lost.

In the spirit of https://twitter.com/Rich_Harris/status/1636738680395014150 bring it back 🙏

**Comment by delight** [comment]
also:

https://github.com/skeletonlabs/create-skeleton-app/blob/e0f7ba2f3ecb5a68953fa99f44d32ed0ed6499fd/README.md?plain=1#L22

**Comment by niktek** [comment]
It's back!
