### ISSUE TITLE
Remove Tailwind Line Clamp plugin

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/create-skeleton-app#23]
Per:
- https://tailwindcss.com/blog/tailwindcss-v3-3#line-clamp-out-of-the-box
- https://github.com/skeletonlabs/skeleton/issues/1238

The Line Clamp feature is now built into Tailwind v3.3, which means we should now remove it from the suggested plugin installs.

**Comment by niktek** [comment]
Done
