### ISSUE TITLE
Adjust grouping and instruction for prompts

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/create-skeleton-app#28]
This is the default SvelteKit CLI installation:

![Screenshot 2023-05-12 at 11 32 25 AM](https://github.com/skeletonlabs/create-skeleton-app/assets/1509726/bd5d4ccc-1394-49a5-9bc8-8ae7b110aa07)

1. I really like the grouping of these four options
2. They include the `(use arrows/space bar)` for instruction

Would be great if we can follow this pattern as well!

**Comment by niktek** [comment]
Of course there turned out to be an undocumented prop that allows for pre-filling values that are received from the argv.  Fixed
