### ISSUE TITLE
No .svelte-kit folder and no .svelte-kit/tsconfig.json file within it for configuring paths

### ISSUE THREAD

**Issue by codelabsprodev** [skeletonlabs/create-skeleton-app#3]
### Current Behavior

Used the CLI to generate the Skeleton Welcome scaffold

Tried to find the .svelte-kit folder and the .svelte-kit/tsconfig.json file in order to configure $lib path. 

Expected

.svelte-kit folder should be available

Actual 

No .svelte-kit folder was found

### Steps To Reproduce

Used the CLI to generate the Skeleton Welcome scaffold

Tried to find the .svelte-kit folder and the .svelte-kit/tsconfig.json file in order to configure $lib path. 

Expected

.svelte-kit folder should be available

Actual 

No .svelte-kit folder was found

### Anything else?

Unable to configure $lib path witout .svelte-kit/tsconfig.json

**Comment by endigo9740** [comment]
@codelabspro I've transferred your issue to the correct repo for this. I'm not sure of a solution to your issue, so I'll let @niktek chime in here. He's the one that built the CLI and can provide better support here.

**Comment by niktek** [comment]
.svelte-kit is generated on 'npm run dev' this will also generate the $lib alias for you if there is a src/lib/ folder - you shouldn't have to do any of this manually

**Comment by codelabsprodev** [comment]
Thanks @niktek Re-running 'nom run dev' solved it for me.
