### ISSUE TITLE
Allow for root level installation

### ISSUE THREAD

**Issue by Hugos68** [skeletonlabs/create-skeleton-app#30]
SvelteKit's CLI allows to install an app in the current directory (by leaving the dir blank), since this CLI is using sk under the hood, can this be made possible?

**Comment by niktek** [comment]
`pnpm create skeleton-app .` ;)

**Comment by Hugos68** [comment]
![afbeelding](https://github.com/skeletonlabs/create-skeleton-app/assets/63101006/2e830018-d0c3-4a70-b047-3a2c7798a407)
Using npm this happens, It does not allow me to install in current dir.

Edit: Oh I see you added the ``.``, my bad, missed it for a second. Still could be a cool option to just hit enter like the sveltekit
 CLI since most folks will be coming from there.
