### ISSUE TITLE
CLI tool installs eslint & prettier regardless of which options were selected

### ISSUE THREAD

**Issue by LukasKepplinger** [skeletonlabs/create-skeleton-app#35]
using the latest version of the CLI (Create Skeleton App 0.0.45) both of therse options create the same template:

What would you like to setup in your project?
- none
- eslint & prettier
![image](https://github.com/skeletonlabs/create-skeleton-app/assets/101792735/7b69faf6-d122-4f04-a491-ff327009cae9)

**Comment by niktek** [comment]
Sorry for the late update on this one - this was fixed a while ago - thanks for the report
