### ISSUE TITLE
Implement support for Skeleton v2

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/create-skeleton-app#37]
With the v2 release candidate fast approaching (ETA august 15th), we'll need to update CSA to support all the various changes coming to the onboarding, setup, and configuration process for new Skeleton projects.

The most notable changes are in regards to the Tailwind plugin, themes, and stylesheets per @AdrianGonz97 [migration guide](https://github.com/skeletonlabs/skeleton/pull/1660). Note that our user-facing documentation has also been updated on the in-[progress v2 pull request](https://github.com/skeletonlabs/skeleton/pull/1730).

I would recommend reading through the following pages top-to-bottom to familiarize yourself with the incoming changes:

- Manual install instructions: https://skeleton-docs-git-v2-skeleton-labs.vercel.app/docs/get-started
- Themes: https://skeleton-docs-git-v2-skeleton-labs.vercel.app/docs/themes
- Theme Generator ("How to Implement"): https://skeleton-docs-git-v2-skeleton-labs.vercel.app/docs/generator

Here's a rough checklist of what this might entail:

- [ ] Ensure the new Skeleton Tailwind plugin is installed on setup alongside the core package:
    - `npm i -D @skeletonlabs/skeleton @skeletonlabs/tw-plugin`
- [ ] Ensure the four `@tailwind` directives are kept in `app.postcss`, rather than removed
- [ ] We now have a choice between `.cjs | .js | .ts` for the `tailwind.config.x` file. (see comments for details)
- [ ] We no longer append `theme-x.css` or `skeleton.css` to the root layout
- [ ] Multiple changes in regards to themes:
    - [ ] Preset theme(s) are now registered within `tailwind.config > Skeleton plugin > theme > preset`
    - [ ] Custom theme(s) are now registered within `tailwind.config > Skeleton plugin > theme > custom`
    - [ ] The active theme is now set via the `data-theme` attribute on the body tag in `app.html`
    - [ ] Theme "extras" are now referred to as `enhancements` and set within the registered theme settings
    
(note that the list above may not be exhaustive, but should cover the most critical items)

**Comment by endigo9740** [comment]
@AdrianGonz97 I would welcome a review of the list above, let me know if I missed anything here.

@niktek let us know if you need someone else to jump in and help implement. I'm sure Mahmoud or someone would be willing and able!

**Comment by AdrianGonz97** [comment]
>  We now have a choice between .cjs | .js | .ts for the tailwind.config.x file. (prefer .cjs?)

We're going to want to prefer `.js` for the TW config. We can also have it change to a `.ts` file as well when the user selects TS, but it's not absolutely necessary if it's too much of a headache to do.
