### ISSUE TITLE
The app.html wrapping div attributes have changed again

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/create-skeleton-app#4]
FYI per Brittney Postma:

> Hey, sorry to ping you on the weekend. I don't have time to file an issue, but wanted to show you this. Not sure if you remember looking at the app.html template on stream the other day and seeing the inline style tag on it display: content. That is an invalid CSS property. The default Svelte template file only has this <div id="svelte">%sveltekit.body%</div> . 

We had a typo here, it's supposed to be `contents`, but doesn't matter as it appears they've removed this again. We'll need to adjust to match on our end. Our inline classes are still relevant though, so keep those please!

**Comment by niktek** [comment]
Fixed during stream!
