### ISSUE TITLE
Dependency issue when isntalling via CLI

### ISSUE THREAD

**Issue by daaa1m** [skeletonlabs/create-skeleton-app#48]
Copying the error report below

```
'Log files:
/Users/da1m/.npm/_logs/2023-12-15T07_53_39_658Z-debug-0.log

# npm resolution error report

While resolving: website@0.0.1
Found: vite@5.0.9
node_modules/vite
  dev vite@"^5.0.3" from the root project

Could not resolve dependency:
peer vite@"^4.1.1" from vite-plugin-tailwind-purgecss@0.1.4
node_modules/vite-plugin-tailwind-purgecss
  dev vite-plugin-tailwind-purgecss@"0.1.4" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by Sarenor** [comment]
It's already adressed upstream: https://github.com/skeletonlabs/skeleton/issues/2312
If you're installing with npm, you can use ``npm i --force``, the plugin will still work, even if the dependencies aren't set up for compatibility yet.

Let's just say that the ecosystem was a bit surprised that SK 2.0 released yesterday :)

**Comment by endigo9740** [comment]
@daaa1m yeah it's an issue with SvelteKit 2 and the PurgeCSS plugin. The maintainer of the plugin is aware of the issue and looking to update. I'd recommend rolling back to SK1 temporarily until that's handled. And monitor the linked issue for progress updates on SK2 support.
